dist: trusty
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-7
    packages:
      - clang-7
